#!/usr/bin/env python3
"""Draw a bell as it looks built: rings stacked, seen from above the rim.

    python3 bell-view.py bell-trumpet-17rings.svg [OUT.svg]

The section drawings show the profile; this shows the object. Isometric, throat at the
back, rim at the front, drawn back to front so each ring occludes the one behind and you
look down into the bore. Ring sizes come out of the cut file, so the picture cannot drift
from what gets cut.

DISPLAY ONLY. Not a cut file.
"""
import sys, re, math, pathlib

C30, S30 = math.cos(math.radians(30)), math.sin(math.radians(30))
def iso(X, Y, Z):
    return ((X - Y)*C30, (X + Y)*S30 - Z)

def widths(d):
    toks = re.findall(r'[MmLlHhVvZzCcSsQqAa]|-?\d*\.?\d+(?:[eE]-?\d+)?', d)
    i = 0; x = y = 0.0; cmd = None; subs = []; cur = None
    def n():
        nonlocal i
        v = float(toks[i]); i += 1; return v
    while i < len(toks):
        if re.fullmatch(r'[A-Za-z]', toks[i]): cmd = toks[i]; i += 1; continue
        if cmd is None: i += 1; continue
        rel = cmd.islower(); c = cmd.upper()
        if c == 'M': dx,dy=n(),n(); x,y=(x+dx,y+dy) if rel else (dx,dy); cur=[x]; subs.append(cur); cmd='l' if rel else 'L'
        elif c == 'L': dx,dy=n(),n(); x,y=(x+dx,y+dy) if rel else (dx,dy); cur.append(x)
        elif c == 'H': v=n(); x=x+v if rel else v; cur.append(x)
        elif c == 'V': v=n(); y=y+v if rel else v; cur.append(x)
        elif c == 'C': n();n();n();n(); dx,dy=n(),n(); x,y=(x+dx,y+dy) if rel else (dx,dy); cur.append(x)
        elif c in ('S','Q'): n();n(); dx,dy=n(),n(); x,y=(x+dx,y+dy) if rel else (dx,dy); cur.append(x)
        elif c == 'A': n();n();n();n();n(); dx,dy=n(),n(); x,y=(x+dx,y+dy) if rel else (dx,dy); cur.append(x)
        else: i += 1
    return [max(v)-min(v) for v in subs if len(v) > 1]

src = sys.argv[1]
s = pathlib.Path(src).read_text()
rings = []
for d in re.findall(r'<path\b[^>]*\bd="([^"]+)"', s):
    w = widths(d)
    if len(w) == 2: rings.append((min(w), max(w)))
rings.sort()
assert rings, f"no rings in {src}"
m = re.search(r'([\d.]+)mm of rise', s)
rise = float(m.group(1)) if m else (1.5 if len(rings) == 5 else 3.0)

TOP, SIDE, EDGE, BG = "#d8b445", "#9c7c1c", "#5e4a10", "#eef2f8"
faces = []
z = 0.0
for a, o in rings:
    ho, ha = o/2.0, a/2.0
    for zz, fill in ((z, SIDE), (z + rise, TOP)):
        pass
    # outer side band, the two faces that face the viewer
    for (ax, ay, bx, by) in ((ho, -ho, ho, ho), (-ho, ho, ho, ho)):
        p = [iso(ax, ay, z), iso(bx, by, z), iso(bx, by, z+rise), iso(ax, ay, z+rise)]
        faces.append((z, "".join(f"{'M' if i==0 else 'L'}{q[0]:.2f},{q[1]:.2f}" for i,q in enumerate(p)) + "Z", SIDE))
    # top annulus: outer square with the aperture as a hole
    outer = [iso(-ho,-ho,z+rise), iso(ho,-ho,z+rise), iso(ho,ho,z+rise), iso(-ho,ho,z+rise)]
    inner = [iso(-ha,-ha,z+rise), iso(ha,-ha,z+rise), iso(ha,ha,z+rise), iso(-ha,ha,z+rise)]
    dd = ("".join(f"{'M' if i==0 else 'L'}{q[0]:.2f},{q[1]:.2f}" for i,q in enumerate(outer)) + "Z" +
          "".join(f"{'M' if i==0 else 'L'}{q[0]:.2f},{q[1]:.2f}" for i,q in enumerate(inner)) + "Z")
    faces.append((z + 0.001, dd, TOP))
    z += rise
faces.sort(key=lambda f: f[0])

pts = [(float(x), float(y)) for x, y in re.findall(r'([-\d.]+),([-\d.]+)', "".join(f[1] for f in faces))]
x0 = min(p[0] for p in pts); x1 = max(p[0] for p in pts)
y0 = min(p[1] for p in pts); y1 = max(p[1] for p in pts)
M = 10.0
W, H = x1-x0+2*M, y1-y0+2*M
body = "\n".join(f'    <path d="{d}" fill="{c}" fill-rule="evenodd" stroke="{EDGE}" stroke-width="0.25"/>'
                 for _, d, c in faces)
dst = sys.argv[2] if len(sys.argv) > 2 else pathlib.Path(src).stem + "-view.svg"
pathlib.Path(dst).write_text(
    f'<svg xmlns="http://www.w3.org/2000/svg" width="{W:.1f}mm" height="{H:.1f}mm"\n'
    f'     viewBox="{x0-M:.1f} {y0-M:.1f} {W:.1f} {H:.1f}" role="img"\n'
    f'     aria-label="A {len(rings)}-ring bell seen from above the rim: square rings stacked '
    f'and widening toward the viewer, the bore visible down the middle">\n'
    f'  <!-- DISPLAY ONLY - not a cut file. Generated by bell-view.py from {pathlib.Path(src).name}. -->\n'
    f'  <rect x="{x0-M:.1f}" y="{y0-M:.1f}" width="{W:.1f}" height="{H:.1f}" fill="{BG}"/>\n'
    f'{body}\n</svg>\n')
print(f"  {dst}: {len(rings)} rings, {W:.0f} x {H:.0f}mm")
